# Generated by Django 3.2.9 on 2021-11-29 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de ciudad')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_consulta', models.DateTimeField(auto_now_add=True, verbose_name='Hora de consulta')),
                ('temperatura', models.FloatField(verbose_name='Temperatura ciudad')),
                ('humedad', models.PositiveIntegerField(verbose_name='Humedad de ciudad')),
                ('velocidad_viento', models.FloatField(verbose_name='Velocidad del viento')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.ciudad', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
    ]
