# Generated by Django 3.2.9 on 2021-11-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_alter_consulta_hora_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='hora_consulta',
            field=models.CharField(max_length=150, verbose_name='Hora de consulta'),
        ),
    ]
